# Generated by Django 4.2.1 on 2023-06-08 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=50)),
                ('prenom_client', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('commune', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('photo_client', models.FileField(upload_to='avatar')),
                ('numero_cni', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OperateurPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_operateur', models.CharField(max_length=20)),
                ('deep_link', models.CharField(max_length=100,null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prestataire', models.CharField(max_length=50)),
                ('prenom_prestataire', models.CharField(max_length=50)),
                ('date_naissance', models.DateField(null=True)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('biographie', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('photo_prestataire', models.FileField(upload_to='avatar')),
                ('numero_cni', models.CharField(max_length=50, unique=True)),
                ('photo_piece_recto', models.FileField(upload_to='pieces_identite')),
                ('photo_piece_verso', models.FileField(upload_to='pieces_identite')),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=50)),
                ('description_service', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('heure_reservation', models.TimeField()),
                ('status_reservation', models.CharField(choices=[('canceled', 'Annulé'), ('in_progress', 'En cours'), ('finished', 'Terminé'), ('requested', 'Demandé')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestataire')),
            ],
        ),
        migrations.AddField(
            model_name='prestataire',
            name='services',
            field=models.ManyToManyField(to='api.service'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('status_paiement', models.CharField(choices=[('canceled', 'Annulé'), ('paid', 'Payé')], max_length=20)),
                ('mode_paiement', models.CharField(choices=[('cash', 'Espèces'), ('e_pay', 'Paiement Electronique')], max_length=20)),
                ('operateur_paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.operateurpaiement')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.CharField(max_length=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestataire')),
            ],
        ),
        migrations.CreateModel(
            name='AdressePrestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=50)),
                ('cite', models.CharField(max_length=50, null=True)),
                ('numero_residence', models.CharField(max_length=30, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('ville', models.CharField(max_length=50)),
                ('quartier', models.CharField(max_length=50)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestataire')),
            ],
        ),
    ]
